apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envkeeper.fullname" . }}-secret
  labels:
    app: {{ include "envkeeper.name" . }}
    chart: {{ include "envkeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  application.yaml: |
    spring.mail:
      host: {{ .Values.mailConfig.spring.mail.host }}
      port: {{ .Values.mailConfig.spring.mail.port }}
      username: {{ .Values.mailConfig.spring.mail.username }}
      password: {{ .Values.mailConfig.spring.mail.password }}
      properties.mail.smtp:
        auth: {{ .Values.mailConfig.spring.mail.properties.mail.smtp.auth }}
        ssl.enable: {{ .Values.mailConfig.spring.mail.properties.mail.smtp.ssl.enable }}
    jhipster:
      mail:
        base-url: {{ .Values.mailConfig.jhipster.mail.baseUrl }}
        from: {{ .Values.mailConfig.jhipster.mail.from }}
    kafka:
      bootstrapAddress: {{ .Values.eventHubsLocation | b64enc | quote }}
      eventHubsConnectionString: {{ .Values.eventHubsConnectionString | b64enc | quote }}
      eventHubsName: {{ .Values.eventHubsName | b64enc | quote }}
