apiVersion: v1
kind: Service
metadata:
  name: {{ include "envkeeper.fullname" . }}
  labels:
    app: {{ include "envkeeper.name" . }}
    chart: {{ include "envkeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "envkeeper.fullname" . }}
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
