apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    app: {{ include "envkeeper.name" . }}
    chart: {{ include "envkeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.jwtSecret | b64enc | quote }}
